[performance]
# types: basic, drone, every_other, dropout
types = ["basic", "basic", "drone"]
# performance scale
scale = 'dorian'
# how many patterns to generate
patterns = 40
# performance's tempo in bpm
bpm = 120

[performance.players]
jitter = false
pattern_iterations_minimum = 4
pattern_iterations_maximum = 12

[performance.player.basic]
jitter = true
