[performance]
types = ["basic", "basic"]
# performance scale
scale = 'dorian'
# how many patterns to generate
patterns = 4
# performance's tempo in bpm
bpm = 120

[performance.players]
jitter = false
pattern_iterations_minimum = 1
pattern_iterations_maximum = 1

[performance.player.basic]
jitter = false
