NOTE_EIGHTH = 0.125
NOTE_QUARTER = 0.25
NOTE_HALF = 0.5
NOTE_WHOLE = 1.0
DOTTED = 1.5
NOTE_LENGTHS = [
    NOTE_EIGHTH,
    NOTE_QUARTER,
    NOTE_HALF,
    NOTE_WHOLE,
    NOTE_EIGHTH * DOTTED,
    NOTE_QUARTER * DOTTED,
    NOTE_HALF * DOTTED,
    NOTE_WHOLE * DOTTED,
]
